theme: minima
title: My awesome page
author: akar-0
email: 
description: > # this means to ignore newlines until "baseurl:"
  Hi everybody.

# social links
github_username:  akar-0 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
